services:
#    kit_form.example:
#        class: Kit\FormBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    kit_form.form.data_transformer_date:
        class: Kit\FormBundle\Form\DateTransformer\DateTransformer
    Kit\FormBundle\Form\DateTransformer\DateTransformer: "@kit_form.data_transformer_date"